# Generated by Django 4.2.4 on 2024-03-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mark_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.content', verbose_name='ID контента'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.content', verbose_name='ID контента'),
        ),
    ]
