# Generated by Django 5.0.1 on 2024-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Отметка', 'verbose_name_plural': 'Отметки'},
        ),
        migrations.AlterField(
            model_name='article',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='article',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
