# Generated by Django 5.0.1 on 2024-02-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=15, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=15, verbose_name='Широта')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('content_id', models.IntegerField(verbose_name='ID контента')),
            ],
        ),
    ]
