# Generated by Django 5.0.3 on 2024-03-27 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0003_content_rename_article_mark"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="Mark",
        ),
    ]
